services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: ev_rental_go_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: ev_rental_go
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ev_rental_go_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ev_rental_go_mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/acl.conf:/mosquitto/config/acl.conf:ro
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - mosquitto_data:/mosquitto/data

volumes:
  postgres_data:
  mosquitto_data:
