#!/usr/bin/env node
/**
 * board.js — สร้าง docs/backlog/board.md จากไฟล์ task และ intent
 *
 *   node .claude/board.js            เขียน board.md ใหม่
 *   node .claude/board.js --check    แค่บอกว่า board ปัจจุบันตรงกับที่ควรเป็นไหม (exit 1 ถ้าไม่ตรง)
 *
 * ทำไมต้องมี: เดิม /done ต้องเขียนข้อเท็จจริงเดียวกัน 3 ที่ (board.md, tasks/*.md, import.csv)
 * ทุกครั้ง = token ซ้ำ 3 เท่า และมีโอกาส drift ตลอด ตอนนี้ **ไฟล์ task คือ source of truth ตัวเดียว**
 * board เป็นแค่ view ที่ generate ได้ (และ session-context.js ยังอ่าน board ได้เหมือนเดิม)
 *
 * frontmatter ของ task ที่ใช้: id title type milestone status priority estimate depends_on
 *                              assignee branch started closed commit blocked_by blocked_reason
 * frontmatter ของ intent ที่ใช้: id title source status created
 *
 * ไม่มี dependency — Node ล้วน
 */
const fs = require('node:fs');
const path = require('node:path');

const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const ROOT = path.resolve(args.find((a) => !a.startsWith('--')) || process.cwd());
const rel = (p) => path.join(ROOT, p);
const exists = (p) => fs.existsSync(rel(p));
const read = (p) => fs.readFileSync(rel(p), 'utf8');
const listMd = (dir) => (exists(dir) ? fs.readdirSync(rel(dir)).filter((f) => f.endsWith('.md') && !f.startsWith('_')).sort() : []);

function frontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const f = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (/^\s*#/.test(line)) continue;
    const kv = line.match(/^([a-zA-Z_-]+):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].replace(/\s+#.*$/, '').trim();
    if (/^\[.*\]$/.test(v)) v = v.slice(1, -1).split(',').map((s) => s.trim()).filter(Boolean);
    f[kv[1]] = v;
  }
  return f;
}
const ph = (v) => !v || /^<|T-000|xxx|\.\.\./.test(String(v));
const cell = (v) => (ph(v) ? '' : Array.isArray(v) ? v.join(' ') : String(v)).replace(/\|/g, '\\|');
const P = { P0: 0, P1: 1, P2: 2, P3: 3 };
const idNum = (id) => parseInt(String(id).replace(/\D/g, ''), 10) || 0;

const tasks = listMd('docs/backlog/tasks')
  .map((f) => frontmatter(read(`docs/backlog/tasks/${f}`)))
  .filter((fm) => fm && fm.id && fm.status);
const intents = listMd('docs/intents')
  .map((f) => ({ file: f, fm: frontmatter(read(`docs/intents/${f}`)) }))
  .filter(({ fm }) => fm && fm.id);

const byStatus = (s) => tasks.filter((t) => t.status === s);
const sortTodo = (a, b) => (P[a.priority] ?? 9) - (P[b.priority] ?? 9) || idNum(a.id) - idNum(b.id);
const doneIds = new Set(byStatus('done').map((t) => t.id));
const depsMet = (t) => !Array.isArray(t.depends_on) || t.depends_on.every((d) => ph(d) || doneIds.has(d));

const table = (headers, rows) =>
  [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');

const projectName = (() => {
  try { return read('docs/planning/_state.md').match(/ชื่อโปรเจกต์:\s*(.+)/)?.[1]?.trim(); } catch { return null; }
})() || path.basename(ROOT);
const today = new Date().toISOString().slice(0, 10);

const milestones = [...new Set(tasks.map((t) => t.milestone).filter((m) => !ph(m)))].sort();
const summary = milestones.map((m) => {
  const ts = tasks.filter((t) => t.milestone === m);
  const done = ts.filter((t) => t.status === 'done');
  const left = ts.filter((t) => t.status !== 'done');
  const est = left.reduce((s, t) => s + (parseFloat(t.estimate) || 0), 0);
  return [m, ts.length, done.length, left.length, est ? `${est} session` : ''];
});

const out = `# กระดานงาน — ${projectName}

<!-- generated by board.js — อย่าแก้ไฟล์นี้ด้วยมือ แก้ที่ docs/backlog/tasks/<ID>.md แล้วรัน node .claude/board.js -->

> **source of truth คือไฟล์ใน \`docs/backlog/tasks/\`** ไฟล์นี้เป็น view ที่ generate จากไฟล์เหล่านั้น
> อัปเดตล่าสุด: ${today}

## กฎ
- \`in-progress\` ได้ **ทีละ 1 task ต่อคน** เท่านั้น
- ทุก task ที่ \`blocked\` ต้องระบุว่าติดอะไร (\`blocked_reason:\` ในไฟล์ task)
- งานใหม่ทุกชิ้นเข้าทาง \`docs/intents/\` ก่อน แล้วค่อยกลายเป็น task (ยกเว้น \`track: trivial\`)
- เปลี่ยนสถานะ = แก้ \`status:\` ในไฟล์ task แล้วรัน \`node .claude/board.js\`

---

## 📥 Intent รอตัดสิน
${table(['ID', 'เรื่อง', 'มาจากไหน', 'เข้ามาเมื่อ', 'สถานะ'],
  intents.filter(({ fm }) => ['draft', 'review'].includes(fm.status)).map(({ fm }) => [fm.id, fm.title, fm.source, fm.created, fm.status]))}

---

## 🔥 In Progress
${table(['ID', 'งาน', 'ประเภท', 'ใครทำ', 'เริ่มเมื่อ'], byStatus('in-progress').map((t) => [t.id, t.title, t.type, t.assignee, t.started]))}

## 👀 Review
${table(['ID', 'งาน', 'branch', 'รออะไร'], byStatus('review').map((t) => [t.id, t.title, t.branch, t.review_waiting || 'คนอนุมัติ']))}

## 📋 Todo (พร้อมทำ เรียงตาม priority → id)
${table(['ID', 'งาน', 'ประเภท', 'M', 'P', 'ประมาณ', 'ขึ้นกับ', 'dep ครบ'],
  byStatus('todo').sort(sortTodo).map((t) => [t.id, t.title, t.type, t.milestone, t.priority, t.estimate, t.depends_on, depsMet(t) ? '✅' : '⏳']))}

## ⛔ Blocked
${table(['ID', 'งาน', 'ติดอะไร', 'รออะไร', 'ตั้งแต่'], byStatus('blocked').map((t) => [t.id, t.title, t.blocked_reason, t.blocked_by || t.depends_on, t.blocked_since]))}

## 📦 Backlog
${milestones.map((m) => {
  const rows = byStatus('backlog').filter((t) => t.milestone === m).sort(sortTodo);
  return `### ${m}\n${rows.length ? table(['ID', 'งาน', 'ประเภท', 'P', 'ประมาณ'], rows.map((t) => [t.id, t.title, t.type, t.priority, t.estimate])) : '_ว่าง_'}`;
}).join('\n\n') || '_ยังไม่มี task ที่ระบุ milestone_'}

## ✅ Done
${table(['ID', 'งาน', 'ปิดเมื่อ', 'commit'], byStatus('done').sort((a, b) => idNum(b.id) - idNum(a.id)).map((t) => [t.id, t.title, t.closed, t.commit]))}

---

## สรุป
${table(['Milestone', 'ทั้งหมด', 'เสร็จ', 'เหลือ', 'ประมาณที่เหลือ'], summary)}
`;

const target = 'docs/backlog/board.md';
if (CHECK) {
  const current = exists(target) ? read(target) : '';
  const strip = (s) => s.replace(/อัปเดตล่าสุด: \d{4}-\d{2}-\d{2}/, '').replace(/\r\n/g, '\n').trim();
  if (strip(current) === strip(out)) { console.log('board.md ตรงกับไฟล์ task แล้ว'); process.exit(0); }
  console.log('board.md ไม่ตรงกับไฟล์ task — รัน node .claude/board.js');
  process.exit(1);
}
fs.mkdirSync(path.dirname(rel(target)), { recursive: true });
fs.writeFileSync(rel(target), out);
console.log(`เขียน ${target}: ${tasks.length} task, ${intents.length} intent`);
